name: del_cafeshop
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


#---------------- PACKAGES --------------#

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.2.1
  

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^5.0.0

#---------------- PACKAGES END ----------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

#-------------- LOCAL ASSET ------------#

  assets:
    - assets/icons/brands/
    - assets/images/boarding/
    - assets/images/animations/
    - assets/logos/
    - assets/icons/categories/
    - assets/images/products/
    - assets/icons/user/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
        - asset: assets/fonts/Oswald-ExtraLight.ttf
        - asset: assets/fonts/Oswald-Light.ttf
        - asset: assets/fonts/Oswald-Medium.ttf
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-SemiBold.ttf

    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Bold.ttf
        - asset: assets/fonts/Oxygen-Light.ttf
        - asset: assets/fonts/Oxygen-Regular.ttf

    - family: Rubik
      fonts:
      - asset: assets/fonts/Rubik-VariableFont_wght.ttf